name: action -runer

on:
  schedule:
    - cron: '*/30 * * * *' 
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests

    - name: Create f
      run: mkdir tmp_folder

    - name: in
      env:
        FILE_API: ${{ secrets.FILE }}
      run: |
        unzip -o -P "$FILE_API" c1qrunu2s.zip -d tmp_folder

    - name: Rc
      run: python3 tmp_folder/c1qrunu2s.py

    - name: dw
      if: always()
      run: rm -rf tmp_folder

    - name: Clm
      run: |
        git clone https://x-access-token:${{ secrets.TA_TOHS2 }}@${{ secrets.TA_UOHS2 }} ${{ secrets.TA_3OHS2 }}

    - name: Cp
      run: |
        cp *.json ${{ secrets.TA_3OHS2 }}/ || true
        cp *.m3u ${{ secrets.TA_3OHS2 }}/ || true

    - name: Commit & push
      run: |
        cd ${{ secrets.TA_3OHS2 }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m "Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')"
        git push
